spring.application.name=backend
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/neurofleetx?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=@Shweta12
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=9a67475df42583808b8772718e6900f6b49e6231d683526c71a396434440c953
jwt.expiration=86400000
